### ISSUE TITLE
Printer 80mm

### ISSUE THREAD

**Issue by fernandodeveloper** [DantSu/PrinterThermal-ESCPOS-Android#1]
Hi! Its possible do increment size text in 80mm? de big is very slow in 80mm.

Congratulations for u work

**Comment by DantSu** [comment]
I don't have 80mm printer. I can't test this.
You have to try by yourself, sorry.

Thanks for your feedback.

**Comment by fernandodeveloper** [comment]
I have an 80mm. Do you have list commands or similar of ESC/POS To be able to try to increase?

I searched for a list or something related to commands but did not find it.

**Comment by DantSu** [comment]
I have all done with this pdf. It's wasn't easy ^^ :
http://www.starmicronics.com/support/mannualfolder/escpos_cm_en.pdf
It's all ESC/POS command.
