### ISSUE TITLE
printFormattedText add space every times

### ISSUE THREAD

**Issue by taphuong** [DantSu/PrinterThermal-ESCPOS-Android#11]
![5a2c571ae30e1850411f](https://user-images.githubusercontent.com/41438033/76599016-a5a64c80-6536-11ea-9994-a95970557fbe.jpg)
![Untitled](https://user-images.githubusercontent.com/41438033/76599283-4268ea00-6537-11ea-8627-36974b0024c4.png)

I don't want "printFormattedText" add space every times. How to fix it ?

**Comment by DantSu** [comment]
You have to use `StringBuilder` and do a `printFormattedText` only one time.

```java
StringBuilder textToPrint = new StringBuilder();

textToPrint
    .append("[L]<b>")
    .append(my_variable)
    .append("</b>[R]")
    .append(my_variable_2)
    .append("\n");

textToPrint.append("[L]" + my_variable_3 + "\n");

Printer printer = new Printer(BluetoothPrinters.selectFirstPairedBluetoothPrinter(), 203, 48f, 32);
printer.printFormattedText(textToPrint.toString());
```

**Comment by taphuong** [comment]
thanks a lot for your help.
How to print vietnamese?
ex: "Cảm ơn rất nhiều"

**Comment by DantSu** [comment]
You can't, it's setup for Western Europe (ISO 8859-1). Sorry. you can write only latin characters.

I add this to the TODO list.
