### ISSUE TITLE
Remove /app example (androidx)

### ISSUE THREAD

**Issue by IsaaX** [DantSu/PrinterThermal-ESCPOS-Android#12]
Hey, I really like this libraries potential and am directly interested in the text parser for generating esc pos commands. My needs don't rely on bluetooth (not yet at least) and have a need to network pos printers instead. My team and I would be interested in helping maintain this library for our printing needs but the biggest limitation to doing so is the `androidx` that is installed for the `/app` on the application used to show an example of the lib. I currently cannot upgrade either due to needing to use expo@35 sdk kit and expo's 36 sdk is not production ready for android which I had to previously revert from. 

I've pulled in the source code directly into my application and have verified that I'm able to compile it correctly and utilize it. So the problem child is the /app directory. I'd suggest moving that into another repo named `<repo-name>-example` and avoid the need for androidx. I'm going to begin working on moving the library to support NetworkPrinter and leverage the textParser so it's bluetooth independent locally and if we are able to remove the /app i'd be happy to put my changes up for a pull request. 

General thoughts is making an interface `IPrinter`  and keep bluetooth and network logic separated and make the text parser just support the interface keeping all bluetooth logic intact while being to extend to NetworkPrinter and potentially SerialPrinter in the future (if needed). 

Keep in mind I'm a java noob (skills lie in javascript land). Would love to hear your thoughts or suggestions that could circumvent these suggestions.

**Comment by DantSu** [comment]
Hi,
Can you share me some code that you use to send data to the printer over network ?

**Comment by IsaaX** [comment]
I sent a pull request with a lot of explanation on my decisions and hopefully we can come to an agreement to make this a bit more modular and supportive of more than just bluetooth :) 

https://github.com/DantSu/PrinterThermal-ESCPOS-Android/pull/14
