### ISSUE TITLE
Demo App

### ISSUE THREAD

**Issue by lainz** [DantSu/PrinterThermal-ESCPOS-Android#13]
Hi, do you have a simple demo application where we can select the printer from a list, and print something like "Hello World"?

Any test application you have in your hard drive will do.

Thanks.

**Comment by DantSu** [comment]
In the main activity of the project : 
https://github.com/DantSu/PrinterThermal-ESCPOS-Android/blob/master/app/src/main/java/com/dantsu/printerthermal/MainActivity.java

Git clone the project and test it.

**Comment by lainz** [comment]
Thanks
