### ISSUE TITLE
Cut letters on Knup 80mm

### ISSUE THREAD

**Issue by JunioJsv** [DantSu/PrinterThermal-ESCPOS-Android#16]
![img](https://user-images.githubusercontent.com/39963398/77693206-bb7c2e80-6f86-11ea-8b07-caaca4682e67.jpeg)

When I use the <font size = 'x'> formatting the print simply comes out with the letters cut off, is there a solution for that?

![Captura de Tela (56)](https://user-images.githubusercontent.com/39963398/77693375-fc744300-6f86-11ea-8c85-b179424e3dae.png)
![Captura de Tela (57)](https://user-images.githubusercontent.com/39963398/77693380-ff6f3380-6f86-11ea-93bc-a77e3aace2b6.png)

**Comment by JunioJsv** [comment]
In the code example the parameters are wrong, because I was testing random values

**Comment by DantSu** [comment]
Hi,
I can't help you for that. It seems to be a printer problem.
The code is open, so you can try to find a fix.
