### ISSUE TITLE
How to print extended ASCII

### ISSUE THREAD

**Issue by pervilla** [DantSu/PrinterThermal-ESCPOS-Android#19]
Sample:
┐ -> alt + 191

└  -> alt + 192
<pre>
 printer.printFormattedText(
"┌──────────────────────────────┬──────────────────────────┐\n" +
"│PERIODO DE FACTURACION        │ 09/04/2020 - 08/05/2020  │\n" +
"└──────────────────────────────┴──────────────────────────┘" +);
</pre>

![print](https://user-images.githubusercontent.com/1031897/86936127-35ce5a00-c103-11ea-8e0c-d48df045f553.jpeg)

**Comment by pervilla** [comment]
I managed to print these characters, using the following encoding:
<pre>
EscPosPrinter printer = new EscPosPrinter(printerConnection, 203, 102f, 32, new EscPosCharsetEncoding("windows-850", 94));            
</pre>
Although I still don't know what the value 94 means, at the end of the line.
![FACT_JLPC_ASCII](https://user-images.githubusercontent.com/1031897/87161126-aacb9c00-c289-11ea-8f91-51b78c774ff2.jpeg)

**Comment by DantSu** [comment]
### This project has moved to https://github.com/DantSu/ESCPOS-ThermalPrinter-Android.

This repository is not maintained anymore.
Please go to https://github.com/DantSu/ESCPOS-ThermalPrinter-Android for documentation, issues, pull request...

### The printer charset ID

Your "94" is the printer charset encoding ID. Each printer have different id for cherset, You have to find this in the printer manual.
You have to find the good charset ID for your charset "windows-850".
For example my printer have this IDs : 
![20200623_151000](https://user-images.githubusercontent.com/4188774/85408231-8b7fff80-b564-11ea-8e13-3dde5f3d7680.jpg)
