### ISSUE TITLE
Drop some lines from printing randomly

### ISSUE THREAD

**Issue by ansar-859** [DantSu/PrinterThermal-ESCPOS-Android#4]
Hello,
It seems really promising and I opted to use it for a project for textual data print. I am using it on Android Mobile PoS device with inbuilt scanner and thermal printer. It works fine when data is few lines but when text is more 15,20 lines then it skips few lines randomly.

**Comment by DantSu** [comment]
I had an equivalent issue. The printer receives too much information compared to the time it has to print.

Try to add this line : `Thread.sleep (PrinterCommands.TIME_BETWEEN_TWO_PRINT);` after line 270 in `/lib/printer/thermal/bluetooth/BluetoothPrinterSocketConnexion.java`

Teel me if it work for you.

**Comment by DantSu** [comment]
Have you try my recommendation for fix this issue ?

**Comment by ansar-859** [comment]
I tried your suggestion and as a result it started printing One line per page. It prints each line after few inches of vertical gap. It is most likely happening because printing got delayed and roller keep ejecting paper. 

This command does not seem to be compatible with my device. Text alignment (left, right, center) commands don't work too.

**Comment by DantSu** [comment]
What are your printer modele ? A link ?

**Comment by ansar-859** [comment]
I am using this all in one device with built-in Printer and Scanner. The device name from system is **IposPrinter**. 
https://www.ocominc.com/products/Q1-Q2-Similar-with-Sunmi-4G-5.5-android-handheld-pos-terminal.html.
Its local vendor in Pakistan and here are product details (https://www.olx.com.pk/item/portable-pos-system-android-all-in-one-iid-1006100085).

**Comment by DantSu** [comment]
`new Printer(BluetoothPrinters.selectFirstPairedBluetoothPrinter(), 200, 48.77f, 32);`
It's seems to be a 200 dpi printer for 48.77mm width printer (384 dot/line). No ? 
It print 32 chars per line ?

**Comment by ansar-859** [comment]
It prints 36 char per line.

**Comment by DantSu** [comment]
https://www.ocominc.com/upfile/product/Q1-Q2-Similar-with-Sunmi-4G-5.5-android-handheld-pos-terminal_8.jpg
On this picture, I see 32 chars per line. 

Do you have dpi printer specification and the number of dot / line on a notice ?

**Comment by ansar-859** [comment]
It is 58mm Thermal Receipt Printer.
Printing Speed is 50mm/S.
It seems to be 30/32 chars per line. I can count 31 chars in test app print. Attached is test page printed by its Testing utility App named **POS Steward**.
![test app](https://user-images.githubusercontent.com/59453953/73459525-d4a69b80-4398-11ea-8275-9e0a24980194.jpeg)

**Comment by DantSu** [comment]
It seems that your printer is a POS printer, not a ESC/POS printer. So it's don't use Epson Standard Code. I think this is the reason why my code doesn't work with your printer.
