### ISSUE TITLE
Printing image shows black in color

### ISSUE THREAD

**Issue by talhamughal10** [DantSu/PrinterThermal-ESCPOS-Android#5]
Hi i have used your code so when i am printing the test image from the same code which you have writter it is showing the image in black color. My image is in .png format and .jpg format but still not getting the desired output.
Can you guide me where i need to update the line the code so that i can print the image perfectly

**Comment by DantSu** [comment]
ESC/POS thermal printer print in black and white color. It can't print with other color. So all image are converted in black and white pixel. Gradient are not possible. Only black pixel and white pixel. So your image must be contrasted to be converted properly. Please show me your image.

**Comment by talhamughal10** [comment]
Year i did it earlier i reallized that ....

But thank you for your response.

in addition kindly guide me if i want to give custom font size to text and make the text italic ... which is not implemented in your printer commands sheet for the text... so can you please tell me what should i do to achieve these tasks?

1: set custom font size
2: make the text italic 
do i need to add their commands code in printercomamnds sheet? and what about the tag do i need to add that as well?

**Comment by DantSu** [comment]
I haven't read about ESC/POS command that allow you to set italic text.
http://www.starmicronics.com/support/mannualfolder/escpos_cm_en.pdf

But if you can do this. You have to update many file. That will not be an easy work.
Do you have any documentation that would contain the ESC / POS command? If yes, please send me a link.

**Comment by talhamughal10** [comment]
Currently i don't have any file which contains the command but yes i am trying to search if i will find i will share it with you....
May i know from where you have written the print command codes so that it would be much easir to study and implement in the code

**Comment by DantSu** [comment]
I just searched, and thermal printers do not seem to be able to print italic text. ESC/POS command for italic text doesn't exists.

**Comment by talhamughal10** [comment]
Oh right... i was also searching for the font style right now but didn't find any resource... for example if i want to use TIme New Roman font style in my reciept so it is also not supported i guess because i have not found any resource regarding this.

**Comment by DantSu** [comment]
Printers thermal contains their own font. You can't choose font. 

If you want do that. You have to create black and white image per line that contain text with font style and family that you want. After you print them with the library.
It's not impossible but it's a relatively heavy work !

**Comment by talhamughal10** [comment]
Thank you so much for your cooperation and guiding me. :)

**Comment by talhamughal10** [comment]
One last thing... can I align image to the left of the text with setting its height and width?

**Comment by DantSu** [comment]
Check warning of <img> tag in the documentation.
> You can't write text on a line that contains `<img></img>`.

Printer thermal doesn't allow to mix line with text and image.

**Comment by talhamughal10** [comment]
yeah i just tried to print it started printing 0000 :-D

**Comment by talhamughal10** [comment]
So that means we can't set height and width of the image too?

**Comment by DantSu** [comment]
In java you can do `Bitmap.createScaledBitmap` to change the size of your picture before use `PrinterTextParserImg.bitmapToHexadecimalString`.

**Comment by talhamughal10** [comment]
HI i hope you will b fine....
I want to ask that can i allow the printing image to print charachters more than 32 characters in a line?
In addition can i set the width the of the page in the printer function
Printer(BluetoothPrinters.selectFirstPairedBluetoothPrinter(), 203, 58f, 40);

**Comment by DantSu** [comment]
The answer is writing in the documentation :

Class : lib.printer.thermal.Printer
Constructor : Printer(BluetoothPrinterSocketConnexion printer, int printerDpi, float printingWidthMM, int nbrCharactersPerLine)

    param BluetoothPrinterSocketConnexion printer : Instance of a connected bluetooth printer
    param int printerDpi : DPI of the connected printer
    param float printingWidthMM : Printing width in millimeters
    param int nbrCharactersPerLine : The maximum number of characters that can be printed on a line.

**Comment by talhamughal10** [comment]
Hi can any one guide me how to print the image in the center using the thermal printer. i am using 80mm paper with black copper USB thermal printer.
I am able to align the text in the center but i am keep on hitting different alignement to printer to center the image and i am stuck here. i have tried setting left margin, using horizontal tab, everyting that can give space to image if alignment is not working.
my image is converted in bytes.

**Comment by DantSu** [comment]
`[C]<img>` Just use the [C] tag.

Have you set a correct printer DPI and printing width in millimeters?

**Comment by talhamughal10** [comment]
i am working or different module but using the escpos commands manually .... i am giving hexadecimal command to print the image in the center. before that i used your library to print the receipt with bluetooth printer.. now i am using usb thermal printer so that i am not finding the way to link your library to my usb printing project thats why i manually started to write commands for printing.

**Comment by talhamughal10** [comment]
can you guide me what would be the command to print the Bitmap converted in bytes 
 byte[] img=PrintCodeAndBitmapDataMaker.printBitmap(bmOut); // this converts the image in bytes which will be sent to the printer
 byte[] pos={0x1d,0x4c,(byte)100,1};// # Set absolute print position to 100
SendDataByte(pos);//it works fine with text but not with image
SendDataByte(img);// here the image will be print... but it is printing left justfied

**Comment by DantSu** [comment]
It's normal, It's heavy work to align image. I can't explain you but you can read my code the answer is inside.

**Comment by talhamughal10** [comment]
in your code you are converting image into the hexadecimal string and parsing the tag

**Comment by talhamughal10** [comment]
Can you please guide me how to print QR code using your library. i have a need of printing QR code which is not stated in your documentation.
Can you guide me please?

**Comment by DantSu** [comment]
The lib don't create QR Code there il no ESC/POS command for that. You have to create a picture of a QRCode and print it like an image.

**Comment by talhamughal10** [comment]
i have created QR code successfully and able to print it but it is printing of left side can you guide me how can i make it center? C tag is not working in my case where i am creating 150 height width QR code
