### ISSUE TITLE
Text Printing using USB printer

### ISSUE THREAD

**Issue by talhamughal10** [DantSu/PrinterThermal-ESCPOS-Android#6]
Hi can i use your library to print the text and image using your library sample with USB Black Copper BC100AC thermal printer?
If yes then can you please guide what steps should i do to achieve this?

**Comment by DantSu** [comment]
It's only for bluetooth thermal printer. USB connections is not supported by the current code. Sorry. 
May be it's not so difficult to implement.

**Comment by EngineerELdorado** [comment]
great library. however how do I include it in my app? I can't see the dependency. Please

**Comment by DantSu** [comment]
There is no dependencies. Just clone it into your project in the `app/src/main/java` directory.
I will add an installation guide in the README.

`cd [PROJECT_DIRECTORY]/app/src/main/java`
`git clone https://github.com/DantSu/PrinterThermal-ESCPOS-Android.git .`

**or** 

download the zip file and unzip the `lib` directory in `[PROJECT_DIRECTORY]/app/src/main/java`

**Comment by DantSu** [comment]
> 
> 
> great library. however how do I include it in my app? I can't see the dependency. Please

Today I added this library to Jitpack, installation by dependency is now available : 

# Installation

Step 1. Add the JitPack repository to your build file. Add it in your root /build.gradle at the end of repositories:

```
allprojects {
    repositories {
        ...
        maven { url 'https://jitpack.io' }
    }
}
```

Step 2. Add the dependency in /app/build.gradle :

```
dependencies {
    ...
    implementation 'com.github.DantSu:PrinterThermal-ESCPOS-Android:1.0.1'
}
```

**Comment by taphuong** [comment]
I don't want "printFormattedText" add space every times. How to fix it ?
