### ISSUE TITLE
How to print QR Code

### ISSUE THREAD

**Issue by talhamughal10** [DantSu/PrinterThermal-ESCPOS-Android#7]
Can you please guide me how to print QR code using your library?

**Comment by DantSu** [comment]
The lib don't create QR Code there il no ESC/POS command for that. You have to create a picture of a QRCode and print it like an image.

**Comment by DantSu** [comment]
Excuse me, there is a command for the QR Code ! But i have'nt implemented this yet. I add this in my to do list. I can't say when I will have the time to develop this feature.

**Comment by talhamughal10** [comment]
i have created QR code successfully and able to print it but it is printing of left side can you guide me how can i make it center? C tag is not working in my case where i am creating 150 height width QR code.... i want to center it

**Comment by DantSu** [comment]
Give me the model of your printer. Have you a link ?

**Comment by talhamughal10** [comment]
Sir i have done it right now thank you so much for being in touch with me ... will be in touch with you :) C tag worked finally i don't know why it worked now

**Comment by DantSu** [comment]
For your information, I just added the QR codes to the library.
