### ISSUE TITLE
`getList()` and how to print variables

### ISSUE THREAD

**Issue by 254Sidney** [DantSu/PrinterThermal-ESCPOS-Android#8]
1) How can i use the getList() method instead of the selectFirstPairedBluetoothPrinter()

2)How can i be able to print depending on the data the user will enter?For example name,ID etc.I don't want to hardcode

**Comment by DantSu** [comment]
### 1) `getList` return an array of [BluetoothPrinterSocketConnexion](https://github.com/DantSu/PrinterThermal-ESCPOS-Android/blob/master/printerthermal_escpos_bluetooth/src/main/java/com/dantsu/printerthermal_escpos_bluetooth/bluetooth/BluetoothPrinterSocketConnexion.java) instance.
```java
        BluetoothPrinters printers = new BluetoothPrinters();
        BluetoothPrinterSocketConnexion[] bluetoothPrinters = printers.getList();
        
        if (bluetoothPrinters != null && bluetoothPrinters.length > 0) {
            for (BluetoothPrinterSocketConnexion printer : bluetoothPrinters) {
                if([YOUR CONDITIONS] && printer.connect()) {
                    return printer;
                }
            }
        }
```
You can use `printer.getDevice()` to get [BluetoothDevice](https://developer.android.com/reference/android/bluetooth/BluetoothDevice) instance.

### 2) Concatenate into the string ? I'm not sure to understand this question. Can you give me an example ?

**Comment by 254Sidney** [comment]
As for the second question,imagine a situation we get input from the user say Name,Email,Date and we want to print that information,how do we pass that information to the printer and format it accordingly.The information being passed is stored in some variable.

**Comment by DantSu** [comment]
```java
Printer printer = new Printer(BluetoothPrinters.selectFirstPairedBluetoothPrinter(), 203, 48f, 32);
printer
    .printFormattedText(
        "[L]<b>" + my_variable  + "</b>[R]" + my_variable_2  + "\n" +
        "[L]" + my_variable_3  + "\n"
    )
    .disconnectPrinter();
```
Just concatenate string. You can use StringBuilder too :
```java
StringBuilder textToPrint = new StringBuilder();

textToPrint
    .append("[L]<b>")
    .append(my_variable)
    .append("</b>[R]")
    .append(my_variable_2)
    .append("\n");

textToPrint.append("[L]" + my_variable_3 + "\n");

Printer printer = new Printer(BluetoothPrinters.selectFirstPairedBluetoothPrinter(), 203, 48f, 32);
printer
    .printFormattedText(textToPrint.toString())
    .disconnectPrinter();
```
Build your string like you want. Read the documentation. All is explain !

**Comment by 254Sidney** [comment]
Thanks a lot DantSu,got it.
